### ISSUE TITLE
Sluit knop lobby selector

### ISSUE THREAD

**Issue by SilvesterNL** [SilvesterNL/Muziekquiz#2]
Nu door het refreshen van de div werkt de sluit knop niet meer op een of andere manier.

**Comment by romanized** [comment]
Door dat die divs in de container steeds een refresh krijgen stopt daardoor de event listener voor de sluit knop ook en werkt die daardoor niet meer (na de 1ste refresh), heb nieuwe JavaScript code toegevoegd (script.js:131) die er voor zorgt dat de event listener actief blijft (en niet wordt vernieuwd). Werkt nu ook voor mobiele devices!
**FIXED**
