### ISSUE TITLE
Kleine bug in het sluit geluid.

### ISSUE THREAD

**Issue by SilvesterNL** [SilvesterNL/Muziekquiz#3]
Als je de lobby selector opent en hem sluit via het kruisje rechts bovenin. Dan hoor je een sluit geluid. Als je dan nog een keer ergens op de pagina drukt dan hoor je ook nog een sluit geluid. Dit gebeurd **_NIET_** als je hem sluit door buiten de div te drukken!

**Comment by romanized** [comment]
Lobby sluiten voor beide methodes zorgt er voor dat een van de event listeners nog actief blijft, dit heb ik opgelost door variable te maken en deze op basis van _true_ of _false_, javascript te laten weten of het geluidje afgespeeld moet worden.
FIXED
